name: syn-mut-rate
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.11.10
  - pandas=1.5.3
  - numpy=1.26.4
  - scipy=1.14.1
  - biopython=1.84
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - notebook=7.2.2
  - pytorch=2.3.1
  - tqdm=4.66.4
  - pip=24.2
  - pip:
      - scikit-learn==1.5.2
